name: Build Release

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
    inputs:
      is_stable:
        description: "Stable Release"
        required: true
        type: boolean
  pull_request:
    types: [closed]
    paths:
      - "source/**"
  push:
    paths:
      - "source/**"

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Extract commit SHA
        id: commit
        run: echo "sha_short=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore dependencies
        run: dotnet restore "source/DualSenseClient/DualSenseClient.csproj"

      - name: Build
        run: |
          dotnet build "source/DualSenseClient/DualSenseClient.csproj" `
            -c Release `
            -p:AssemblyInformationalVersion=${{ steps.commit.outputs.sha_short }}

      - name: Run Unit Tests
        run: dotnet test "test/DualSenseClient.Tests/DualSenseClient.Tests.csproj" -c Release --no-build --verbosity normal

      - name: Publish
        run: |
          dotnet publish "source/DualSenseClient/DualSenseClient.csproj" `
            -c Release `
            -r win-x64 `
            --self-contained false `
            -p:PublishReadyToRun=false `
            -p:PublishSingleFile=false `
            -p:AssemblyInformationalVersion=${{ steps.commit.outputs.sha_short }} `
            -o publish/

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: DualSenseClient
          path: ./publish/
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml
    with:
      is_stable: ${{ inputs.is_stable || false }}
    secrets: inherit
